theme: minima
title: Pyhon for WRR Project [HASA]
author: Aswatha Narayana S
  email: aswatha.narayana94@gmail.com
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
